name: iron
description: "An architecture forged like iron, as solid as armor for your Flutter apps! Focusing on clarity, persistence, and reactivity with zero dependencies."
version: 0.0.3
homepage: https://github.com/endmr11/iron
topics: [architecture, reactive, state-management, dependency-injection, persistence]
documentation: https://endmr11.github.io/system_design/en/mobile/iron-architecture.html
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
